CREATE TABLE "userPermissions" (
    id BIGSERIAL PRIMARY KEY,
    "orgId" BIGINT NOT NULL,
    "userId" BIGINT NOT NULL,
    "isEnabled" BOOLEAN NOT NULL DEFAULT true,
    "projectsCreate" BOOLEAN NOT NULL DEFAULT true,
    "projectsRead" BOOLEAN NOT NULL DEFAULT true,
    "projectsUpdate" BOOLEAN NOT NULL DEFAULT true,
    "projectsDelete" BOOLEAN NOT NULL DEFAULT true,
    "workCreate" BOOLEAN NOT NULL DEFAULT true,
    "workRead" BOOLEAN NOT NULL DEFAULT true,
    "workUpdate" BOOLEAN NOT NULL DEFAULT true,
    "workDelete" BOOLEAN NOT NULL DEFAULT true,
    "milestonesCreate" BOOLEAN NOT NULL DEFAULT false,
    "milestonesRead" BOOLEAN NOT NULL DEFAULT true,
    "milestonesUpdate" BOOLEAN NOT NULL DEFAULT false,
    "milestonesDelete" BOOLEAN NOT NULL DEFAULT false,
    "targetsCreate" BOOLEAN NOT NULL DEFAULT false,
    "targetsRead" BOOLEAN NOT NULL DEFAULT true,
    "targetsUpdate" BOOLEAN NOT NULL DEFAULT false,
    "targetsDelete" BOOLEAN NOT NULL DEFAULT false,
    "commentsCreate" BOOLEAN NOT NULL DEFAULT true,
    "commentsRead" BOOLEAN NOT NULL DEFAULT true,
    "commentsUpdate" BOOLEAN NOT NULL DEFAULT true,
    "commentsDelete" BOOLEAN NOT NULL DEFAULT true,
    "attachmentsCreate" BOOLEAN NOT NULL DEFAULT true,
    "attachmentsRead" BOOLEAN NOT NULL DEFAULT true,
    "attachmentsUpdate" BOOLEAN NOT NULL DEFAULT true,
    "attachmentsDelete" BOOLEAN NOT NULL DEFAULT true,
    "createdBy" BIGINT,
    "updatedBy" BIGINT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ
);
