CREATE TABLE "work" (
    id BIGSERIAL PRIMARY KEY,
    "orgId" BIGINT NOT NULL,
    "projectId" BIGINT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    "statusId" BIGINT NOT NULL,
    "priorityId" BIGINT NOT NULL,
    "milestoneId" BIGINT,
    "targetId" BIGINT,
    "assigneeId" BIGINT,
    "reporterId" BIGINT NOT NULL,
    "dueDate" TIMESTAMPTZ,
    "completedAt" TIMESTAMPTZ,
    "createdBy" BIGINT,
    "updatedBy" BIGINT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updatedAt" TIMESTAMPTZ,
    "isActive" BOOLEAN NOT NULL DEFAULT true
);
